name: deploy

on:
  push:
    branches:
      - main
      - dev

env:
  OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
  OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
  OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
  OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
  OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
  OCI_COMPARTMENT_OCID: ${{ secrets.OCI_COMPARTMENT_OCID }}
  APP_NAME: 'contact-api'
  APP_NAMESPACE: manutencao-de-piscina
  CONTAINER_PORT: 3000
  URL_TO_ASSUME: ${{ secrets.APP_URL }}

jobs:
  get-ocir-repository-and-push:
    runs-on: ubuntu-latest
    name: Get OCIR Repository and Push to OCIR
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    steps:
      - name: Pull Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: Extract environment name
        run: |
          echo "ENVIRONMENT=$(echo ${GITHUB_REF_NAME})" >> $GITHUB_ENV
          if [[ $ENVIRONMENT == "main" ]]; then
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          fi
      - name: Get OCIR Repository
        uses: oracle-actions/get-ocir-repository@v1.2.1
        id: get-ocir-repository
        env:
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
        with:
          name: ${{ env.ENVIRONMENT }}-${{ env.APP_NAME }}
          compartment: ${{ secrets.OCI_CLI_COMPARTMENT_OCID }}
      - name: Get Image Tag
        run: |
          echo "IMAGE_TAG=$(cat package.json | jq -r .version)" >> $GITHUB_ENV

      - name: Login to Oracle Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.OCI_CLI_AUTH_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        with:
          push: true
          platforms: linux/arm64
          file: docker/Dockerfile
          context: .
          tags: |
            ${{ steps.get-ocir-repository.outputs.repo_path }}:latest
            ${{ steps.get-ocir-repository.outputs.repo_path }}:${{ env.IMAGE_TAG }}

  update-kube-template:
    runs-on: ubuntu-latest
    needs: [get-ocir-repository-and-push]
    name: Update template to deployment service and ingress
    steps:
      - name: Pull Code
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.GH_SSH_KEY }}
      - name: Get Image Tag
        run: |
          echo "IMAGE_TAG=$(cat package.json | jq -r .version)" >> $GITHUB_ENV
      - name: Extract environment name
        run: |
          echo "ENVIRONMENT=$(echo ${GITHUB_REF_NAME})" >> $GITHUB_ENV
          if [[ $ENVIRONMENT == "main" ]]; then
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          fi
      - name: Extract API URL
        run: |
          echo "ENVIRONMENT=$(echo ${GITHUB_REF_NAME})" >> $GITHUB_ENV
          if [[ $ENVIRONMENT == "main" ]]; then
            echo "API_URL=${{ env.URL_TO_ASSUME }}" >> $GITHUB_ENV
          else
            echo "API_URL=dev.${{ env.URL_TO_ASSUME }}" >> $GITHUB_ENV
          fi
      - name: Get Ocir Repository
        uses: oracle-actions/get-ocir-repository@v1.2.1
        id: get-ocir-repository
        env:
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
        with:
          name: ${{ env.ENVIRONMENT }}-${{ env.APP_NAME }}
          compartment: ${{ secrets.OCI_CLI_COMPARTMENT_OCID }}
      - name: Remove old Deployment file
        env:
          IMAGE: ${{ steps.get-ocir-repository.outputs.repo_path }}:${{ env.IMAGE_TAG }}
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
          API_URL: ${{  env.API_URL  }}
        run: |
          cp k8s/templates/deployment.tpl k8s/${{ env.ENVIRONMENT }}/deployment.yaml
          sed -i 's|$APP_NAMESPACE|${{ env.APP_NAMESPACE }}|g' k8s/${{ env.ENVIRONMENT }}/deployment.yaml
          sed -i 's|$CONTAINER_IMAGE|${{ env.IMAGE }}|g' k8s/${{ env.ENVIRONMENT }}/deployment.yaml
          sed -i 's|$APP_NAME|${{ env.APP_NAME }}|g' k8s/${{ env.ENVIRONMENT }}/deployment.yaml
          sed -i 's|$CONTAINER_PORT|${{ env.CONTAINER_PORT }}|g' k8s/${{ env.ENVIRONMENT }}/deployment.yaml

          cp k8s/templates/service.tpl k8s/${{ env.ENVIRONMENT }}/service.yaml
          sed -i 's|$APP_NAMESPACE|${{ env.APP_NAMESPACE }}|g' k8s/${{ env.ENVIRONMENT }}/service.yaml
          sed -i 's|$APP_NAME|${{ env.APP_NAME }}|g' k8s/${{ env.ENVIRONMENT }}/service.yaml
          sed -i 's|$CONTAINER_PORT|${{ env.CONTAINER_PORT }}|g' k8s/${{ env.ENVIRONMENT }}/service.yaml

          cp k8s/templates/ingress.tpl k8s/${{ env.ENVIRONMENT }}/ingress.yaml
          sed -i 's|$APP_NAMESPACE|${{ env.APP_NAMESPACE }}|g' k8s/${{ env.ENVIRONMENT }}/ingress.yaml
          sed -i 's|$APP_NAME|${{ env.APP_NAME }}|g' k8s/${{ env.ENVIRONMENT }}/ingress.yaml
          sed -i 's|$CONTAINER_PORT|${{ env.CONTAINER_PORT }}|g' k8s/${{ env.ENVIRONMENT }}/ingress.yaml
          sed -i 's|$URL_TO_ASSUME|${{ env.API_URL }}|g' k8s/${{ env.ENVIRONMENT }}/ingress.yaml

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.3
        with:
          add: k8s
          author_name: AutoCommit
          message: '[#AutoCommit] Release - Changing Deployment Files'
          push: true
